services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "6001:80"

  server-1:
    build: ./
    expose:
      - "6000"

  server-2:
    build: ./
    expose:
      - "6000"

  server-3:
    build: ./
    expose:
      - "6000"
